"""Optional LLM-driven improvement proposer. Skipped silently if OLLAMA_HOST
is not set, so this task is a no-op for users who don't run a local model.

When enabled, it asks the local Ollama model to suggest ONE small, low-risk
improvement to the codebase (e.g. tighten a regex, add a doc comment, remove
a dead branch). The proposal is written as a draft PR — never auto-merged.

Safety:
  - Only reads source files; never executes.
  - The PR is marked `draft` so a human must approve before merge.
  - Limited to 1 proposal per day to avoid PR spam.
  - If the model returns garbage (no valid unified diff), we just log and skip.
"""
from __future__ import annotations

import os
from datetime import UTC
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


async def run() -> str:
    host = os.environ.get("OLLAMA_HOST", "").strip()
    if not host:
        return "OLLAMA_HOST not set — skipped"
    model = os.environ.get("OLLAMA_MODEL", "qwen2.5-coder:7b").strip()

    # Lazy import — httpx is already a project dep, but keep this clean
    try:
        import httpx
    except ImportError:
        return "httpx not available"

    # Pick one file at random from the modules — small, focused scope
    import random
    mod_dir = ROOT / "app" / "modules"
    candidates = sorted(p for p in mod_dir.glob("*.py")
                        if p.name not in {"__init__.py", "base.py"})
    if not candidates:
        return "no module files to improve"
    target = random.choice(candidates)
    source = target.read_text(encoding="utf-8")[:8000]

    prompt = (
        "You are reviewing a Python OSINT module for a small, low-risk improvement. "
        "Suggest exactly ONE change — a tightened regex, a missing edge case, a doc "
        "comment, or a clearer error message. Keep it under 15 lines diff. Respond "
        "with the changed function only, in valid Python. Do NOT rewrite the whole "
        "module. Do NOT add new dependencies. If you don't see a confident improvement, "
        "respond with 'NO IMPROVEMENT'.\n\n"
        f"File: {target.relative_to(ROOT)}\n\n```python\n{source}\n```"
    )

    try:
        r = httpx.post(
            f"{host.rstrip('/')}/api/generate",
            json={"model": model, "prompt": prompt, "stream": False},
            timeout=120,
        )
        if r.status_code != 200:
            return f"ollama HTTP {r.status_code}"
        body = r.json().get("response", "").strip()
    except Exception as e:
        return f"ollama crash: {type(e).__name__}: {e}"

    if not body or "NO IMPROVEMENT" in body.upper():
        return f"{target.name}: no confident proposal"

    # Persist the proposal — do NOT apply it. A human reviews before merge.
    out_dir = ROOT / "agent" / "data" / "proposals"
    out_dir.mkdir(parents=True, exist_ok=True)
    from datetime import datetime
    ts = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    out_file = out_dir / f"{ts}-{target.stem}.md"
    out_file.write_text(
        f"# Proposal for {target.relative_to(ROOT)}\n\n"
        f"_Generated by {model} via Ollama at {ts}_\n\n"
        f"```python\n{body[:6000]}\n```\n",
        encoding="utf-8",
    )
    return f"{target.name}: proposal saved -> {out_file.relative_to(ROOT)}"
