"""Markdown report generator — output suitable for GitHub Issues, Notion, Jira.

Same shape as html_report.render_report() but emits Markdown. Sorted by
severity within each module so the worst findings float to the top.
"""
from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime

from app.core.attack import tids_for
from app.core.types import Hit, HitStatus, Query, QueryResult, Severity

_SEV_ORDER = {Severity.CRITICAL: 0, Severity.HIGH: 1, Severity.MEDIUM: 2,
              Severity.LOW: 3, Severity.INFO: 4}
_SEV_EMOJI = {
    "critical": "🔴", "high": "🟠", "medium": "🟡",
    "low": "🔵", "info": "⚪",
}


def render_markdown(query: Query, result: QueryResult, elapsed_ms: int) -> str:
    by_module: dict[str, list[Hit]] = defaultdict(list)
    for h in result.hits:
        by_module[h.module].append(h)

    n_total = len(result.hits)
    n_found = sum(1 for h in result.hits if h.status == HitStatus.FOUND)
    n_crit = sum(1 for h in result.hits if h.severity == Severity.CRITICAL)
    n_high = sum(1 for h in result.hits if h.severity == Severity.HIGH)
    n_med = sum(1 for h in result.hits if h.severity == Severity.MEDIUM)

    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    out: list[str] = []
    out.append(f"# OSINT report — `{query.value}`")
    out.append("")
    out.append(f"> mytools-osint · {query.kind.value} scan · generated {now}")
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append("| Metric | Value |")
    out.append("|---|---|")
    out.append(f"| Target | `{query.value}` |")
    out.append(f"| Kind | `{query.kind.value}` |")
    out.append(f"| Total hits | **{n_total}** |")
    out.append(f"| Positives (FOUND) | **{n_found}** |")
    out.append(f"| 🔴 Critical | **{n_crit}** |")
    out.append(f"| 🟠 High | **{n_high}** |")
    out.append(f"| 🟡 Medium | **{n_med}** |")
    out.append(f"| Modules engaged | {len(by_module)} |")
    out.append(f"| Duration | {elapsed_ms} ms |")
    out.append("")

    # Critical & high findings up front
    top = sorted(
        (h for h in result.hits if h.severity in (Severity.CRITICAL, Severity.HIGH)),
        key=lambda h: (_SEV_ORDER[h.severity], h.module),
    )
    if top:
        out.append("## ⚠️  Top findings (high + critical)")
        out.append("")
        out.append("| Sev | Module | Source | Finding | Link |")
        out.append("|---|---|---|---|---|")
        for h in top:
            sev = h.severity.value
            url = f"[link]({h.url})" if h.url else ""
            detail = (h.detail or "").replace("|", "\\|")[:160]
            out.append(f"| {_SEV_EMOJI.get(sev,'·')} {sev.upper()} | "
                       f"`{h.module}` | {h.source} | {detail} | {url} |")
        out.append("")

    # Per-module sections
    out.append("## Findings by module")
    out.append("")
    for mod, items in sorted(by_module.items(),
                              key=lambda kv: -sum(1 for h in kv[1] if h.status == HitStatus.FOUND)):
        items_sorted = sorted(items, key=lambda h: (_SEV_ORDER.get(h.severity, 5), h.source))
        n_pos = sum(1 for h in items if h.status == HitStatus.FOUND)
        tids = tids_for(mod)
        tid_str = ""
        if tids:
            tid_links = " · ".join(
                f"[{t}](https://attack.mitre.org/techniques/{t.replace('.', '/')}/)"
                for t in tids
            )
            tid_str = f"  *— ATT&CK: {tid_links}*"
        out.append(f"### `{mod}` — {n_pos} found / {len(items)} probed{tid_str}")
        out.append("")
        out.append("| Sev | Status | Source | Detail | URL |")
        out.append("|---|---|---|---|---|")
        for h in items_sorted:
            sev = h.severity.value
            url = h.url or ""
            url_md = f"[…]({url})" if url else ""
            detail = (h.detail or "").replace("|", "\\|")[:200]
            out.append(f"| {_SEV_EMOJI.get(sev,'·')} | `{h.status.value}` | "
                       f"**{h.source}** | {detail} | {url_md} |")
        out.append("")

    out.append("---")
    out.append(f"_Generated by [mytools-osint](https://github.com/Azizbek16l/mytools-osint) · "
               f"{n_total} hits across {len(by_module)} modules in {elapsed_ms} ms._")
    return "\n".join(out)
